spring:
    datasource:
        username: root
        url: jdbc:mysql://localhost:3306/coffee?serverTimezone=UTC&useSSL=true
        password: 123456
        driver-class-name: com.mysql.cj.jdbc.Driver
server:
    port: 9090

